name: Build and Run Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Configure and Build GraphBLAS
        run: |
          cd deps/GraphBLAS
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel
          sudo cmake --install build

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure