name: Build and Run Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Create GraphBLASTargets.cmake
        run: |
          mkdir -p build/GraphBLAS
          cat > build/GraphBLAS/GraphBLASTargets.cmake << 'EOL'
          if(NOT TARGET SuiteSparse::GraphBLAS)
            add_library(SuiteSparse::GraphBLAS ALIAS graphblas)
          endif()
          EOL

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure